import type { Metadata } from "next";
import "./globals.css"; // Global styles
import Header from "@/components/header";
import PageTransition from "@/components/PageTransition";
import StairTransitions from "@/components/StairTransitions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
        <link rel="preload" href="/fonts/your-font.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
      </head>
      <body className="font-secondary" style={{ fontFamily: 'JetBrains Mono, monospace' }}>
        <Header />
        <StairTransitions />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
